name: compile game-server jar

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Build the game-data module
        working-directory: ntts-game-data
        run: |
          make

      - name: Build the server
        run: |
          make

      - name: Deploy jar
        run: |
          mvn deploy -Dregistry=https://maven.pkg.github.com/EagleoutIce -Dtoken=GH_TOKEN
